# Generated by Django 5.1.7 on 2025-03-16 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_address', models.CharField(max_length=50)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_token', models.CharField(max_length=50)),
                ('associated_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
