# Generated by Django 5.1.7 on 2025-03-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_associated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
