# Generated by Django 4.2.20 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_wallet_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='preferred_payment_methods',
            field=models.TextField(default='[]'),
        ),
    ]
