# Generated by Django 5.1.7 on 2025-04-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_transaction_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
