# Generated by Django 5.1.7 on 2025-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_wallet_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='on_chain_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
