# Generated by Django 4.2.20 on 2025-04-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_convert_preferred_payment_methods_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='preferred_payment_methods',
            field=models.JSONField(default=list),
        ),
    ]
