# Generated by Django 5.1.7 on 2025-04-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_transaction_on_chain_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='on_chain_transaction_id',
            new_name='transaction_signature',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_address',
        ),
    ]
