# Generated by Django 5.1.7 on 2025-05-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_on_chain_transaction_id_transaction_transaction_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('confirmed', 'Confirmed'), ('finalized', 'Finalized')], default='pending', max_length=10),
        ),
    ]
