# Generated by Django 5.1.7 on 2025-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_transaction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('confirmed', 'Confirmed'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
