name: Python CI Workflow

on:
  pull_request:
    branches:
      - main  # Trigger the action for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: your_project.settings  # Add this line to set the settings module

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the Python version for your app

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install  # Install Playwright browsers

      - name: Run unit and integration tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run your unit and integration tests

      - name: Generate code coverage report
        run: |
          pip install coverage  # Install coverage tool
          coverage run -m pytest tests/  # Run tests with coverage
          coverage report  # Display coverage in terminal
          coverage html  # Generate HTML report (optional)

      - name: Launch application and run end-to-end test
        run: |
          nohup python manage.py runserver &  # Launch the Django app in the background
          sleep 5  # Wait for the server to start
          pytest tests/test_end_to_end.py  # Run the end-to-end tests with Playwright

      - name: Upload coverage results to Codecov (optional)
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml  # If you're using Codecov for coverage analysis
