# Generated by Django 5.1.7 on 2025-03-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='payment_token',
            field=models.CharField(default='default_token', max_length=50),
        ),
    ]
