name: Django CI

on:
  push:
    branches:
      - main
      - testing
      - review
  pull_request:
    branches:
      - main
      - testing
      - review

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov

      - name: Run Migrations
        run: |
          cd ledgerpay
          python manage.py migrate

      - name: Run Unit & Integration Tests
        run: |
          cd ledgerpay
          pytest payments/tests/ --cov=payments --cov-report=xml --ignore=payments/tests/e2e

      - name: Upload Unit Test Coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./ledgerpay/coverage.xml
          flags: unittests
          name: codecov-unit-tests

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov playwright
          playwright install

      - name: Run Migrations
        run: |
          cd ledgerpay
          python manage.py migrate

      - name: Start Django Server with Coverage
        run: |
          cd ledgerpay
          coverage run manage.py runserver 8000 &
          sleep 7  # Wait for the server to start

      - name: Run E2E Tests
        run: |
          cd ledgerpay
          pytest payments/tests/e2e --cov=payments --cov-report=xml --cov-append

      - name: Stop Django Server
        run: |
          pkill -f "python manage.py runserver"

      - name: Upload E2E Test Coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./ledgerpay/coverage.xml
          flags: e2etests
          name: codecov-e2e-tests