name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ledgerpay  # ✅ Move into the correct directory
        run: pip install -r ../requirements.txt  # ✅ Use correct path

      - name: Run Migrations
        working-directory: ledgerpay  # ✅ Move into the correct directory
        run: python manage.py migrate

      - name: Run Tests
        working-directory: ledgerpay  # ✅ Move into the correct directory
        run: pytest --ds=ledgerpay.settings --cov=withdrawal --cov-report=term-missing

