name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd ledgerpay  # Move into the correct directory
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          cd ledgerpay  # Move into the correct directory
          python manage.py migrate

      - name: Run Tests
        run: |
          cd ledgerpay  # Move into the correct directory
          pytest --ds=ledgerpay.settings --cov=withdrawal --cov-report=term-missing

